### ISSUE TITLE
?????

### ISSUE THREAD

**Issue by exopss** [MakkusuOtaku/mc-printer#7]
x = Math.floor(image.shape[0]*x);
                             ^

TypeError: Cannot read properties of undefined (reading 'shape')
    at getBlock (/home/exops/Downloads/sex/mc-printer-main/index.js:322:30)
    at buildImage (/home/exops/Downloads/sex/mc-printer-main/index.js:360:29)
    at drawImage (/home/exops/Downloads/sex/mc-printer-main/index.js:109:5)
    at async runCommand (/home/exops/Downloads/sex/mc-printer-main/index.js:145:13)

**Comment by MakkusuOtaku** [comment]
I think this happens when the image doesn't exist or the path is wrong.

**Comment by exopss** [comment]
ok
